//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDPC11_G5_Ristorante {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm validateLogin;
		
		protected System.Web.UI.WebControls.TextBox TXTUser;
		
		protected System.Web.UI.WebControls.TextBox TXTPsw;
		
		protected System.Web.UI.WebControls.Button BTNSubmit;
		
		protected System.Web.UI.WebControls.Button BTNReg;
		
		protected System.Web.UI.WebControls.Label LBLOutput;
	}
}
