//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDPC11_G5_Ristorante {
	
	
	public partial class RegistrazioneUtente {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox TXTCognome;
		
		protected System.Web.UI.WebControls.TextBox TXTEmail;
		
		protected System.Web.UI.WebControls.TextBox TXTPhone;
		
		protected System.Web.UI.WebControls.TextBox TXTUsr;
		
		protected System.Web.UI.WebControls.TextBox TXTPsw;
		
		protected System.Web.UI.WebControls.Button BTNSubmit;
	}
}
